### ISSUE TITLE
Why does this library require php 7.1 and not just 7.0?

### ISSUE THREAD

**Issue by pwaterz** [nicebooks-com/isbn#1]

**Comment by BenMorel** [comment]
Hi, some reasons have been provided on [gophp71.org](https://gophp71.org/):
https://www.tomasvotruba.cz/blog/2017/06/05/go-php-71/

Plus, active support for PHP 7.0 has been dropped 6 months ago, and security support will expire in 5 months:
http://php.net/supported-versions.php

On 3 Dec 2018, PHP 7.0 will effectively be dead.

**Comment by BenMorel** [comment]
By the way, you can still use version `0.1.0`, which is PHP 5.4+ compatible.
